# Generated by Django 4.1.7 on 2023-04-10 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=500)),
                ('nostr_id', models.CharField(max_length=500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nostr.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nostr_id', models.CharField(max_length=500)),
                ('awardee_pubkey', models.CharField(max_length=500)),
                ('badge_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nostr.badgedefinition')),
            ],
        ),
    ]
